 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5100
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 657-656-268
Traceback (most recent call last):
  File "/Users/rehandesilva/Gallery Cafe Backup/Testing /app.py", line 34, in <module>
    app.run(debug=True, port=5200)
  File "/Users/rehandesilva/Gallery Cafe Backup/Testing /.venv/lib/python3.9/site-packages/flask/app.py", line 625, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/rehandesilva/Gallery Cafe Backup/Testing /.venv/lib/python3.9/site-packages/werkzeug/serving.py", line 1106, in run_simple
    run_with_reloader(
  File "/Users/rehandesilva/Gallery Cafe Backup/Testing /.venv/lib/python3.9/site-packages/werkzeug/_reloader.py", line 448, in run_with_reloader
    ensure_echo_on()
  File "/Users/rehandesilva/Gallery Cafe Backup/Testing /.venv/lib/python3.9/site-packages/werkzeug/_reloader.py", line 428, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
